[#create_springboot]
= Creating a Spring Boot Quickstart Project

. In your {osio} home page, double-click your new space.
. In your space's dashboard, click btn:[Add to space].
. Select `Create a new Quickstart project`.
. In the `Application Wizard`:
.. Click a project type from the displayed icons. For this example, click btn:[Spring Boot - HTTP].
.. Click btn:[Next].
.. Select your organization name from the options in the `Organisation` field. For this example, use the default value, which is the organization name assigned to your personal GitHub account.
.. In the `OpenShift Project Name` field, add *myspringboot* as the name for your project.
.. Leave the default value for the `Group Id` and `Version` fields and click btn:[Next].
.. Select a build pipeline strategy. For this example, use the default value (`Release, Stage, Approve and Promote`) and click btn:[Next].
+
NOTE: Pipelines allow developers to create a repeatable, reliable, and incrementally improving process to move the software from code to the execution environment.
.. The `Build Config` screen displays the details for your `Jenkins Space` and options for web hooks and triggering builds. Use the default options for these fields and click btn:[Finish].
.. The `Summary` screen displays your selected options. Click btn:[Ok] to continue.

Your new Spring Boot project is now created and added to your GitHub account.
