[#optional_detailed_views]
= (Optional) Detailed Views

Optionally, you can see an experimental detailed view for the `Test`, `Stage`, and `Run` environments. This view displays the environment deployments, pods, events, and other information.

View the details for the `Environment` as follows:

. Opt in for this *experimental feature*:
.. On the top right corner of the page, click your name.
.. Click btn:[Profile] in the displayed options.
.. In the `Profile` page, click btn:[Update Profile].
.. Read the `Experimental Features` details and click *I agree to the terms above and would like to opt into exprimental features* to agree.
.. Click btn:[Update] to save your changes.
.. On the top left side of the page, click your username.
.. Click the name of your Space to return to the Space's dashboard. page to view each

. At the top of the page, click btn:[Create].

. From the options displayed, click btn:[Environments]. This view displays the details for each project on *Run* and *Stage*.


Optionally wiew the pipeline progress in OpenShift Online as follows:

. Navigate to https://manage.openshift.com/ in a new browser tab and log in to your account.

. Click btn:[Open Web Console] to view the console.

. From the list of projects, click btn:[USERNAME-jenkins].

. On the left side of the page, click btn:[Builds] and then btn:[Builds] again in the menu options. Your project's new build displays here.

. Click the name of the build to view details. If required, use this console to monitor the build progress.
