[#reduce_mem]
= Reduce the Boot Spring Project's Memory Usage

Your {osio} space now has two quickstart projects running: the Hello World Vert.x project and the new Spring Boot HTTP project. These two projects share the same limited memory resources in OpenShift Online. You must therefore reduce the memory usage for these projects.

See <<opt_mem.adoc>> to optimize memory usage for the Hello World project and use the following instructions for the Spring Boot project:

. In your Che workspace, expand the `src` > `main` > `fabric8` folders.

. Right-click the `fabric8` folder and select `New` > `File`.

. Name the new file *deployment.yaml*.

. Copy the following file's contents to your new yaml file: https://raw.githubusercontent.com/burrsutter/vertx-eventbus/master/src/main/fabric8/deployment.yml[deployment.yaml].
+
WARNING: Spaces are meaningful in yaml files. Ensure that the correct spacing is copied into your yaml file from the link.
+
. Use kbd:[Ctrl+s] (or kbd:[Cmd+s] for macOS) to save your changes.
