FROM fedora:27

MAINTAINER Robert Kratky <rkratky@redhat.com>

# Install asciidoctor
RUN dnf install -y findutils which rubygem-asciidoctor rubygem-asciidoctor-pdf libxml2 && \
    dnf clean all

COPY scripts/ scripts/
COPY docs/ docs/

ENTRYPOINT ["sh", "scripts/build_guides.sh"]
