[id="about_work_items"]
= About work items

Work items are measurable units of work within a link:user-guide.html#about_spaces[space] that can be tracked. They are captured representations of work, assigned to a team member. Work items track data such as user stories, scenarios, tasks, and bugs.

The {ct} planner is a task or work item tracker to plan and execute your project work. It provides an _Agile_ development process based planning template to create different types of work items to track your work.

You can use the planner to change the attributes of a work item, associate them with iterations and areas.
You can assign them to collaborators in your space, track their progress, and filter them according to your requirements.

The planner displays all work items in a flat or hierarchical list. These work items are grouped based on the agile work item types. It lists the link:user-guide.html#about_iterations[Iterations] and the work items associated to these iterations enabling effective execution of the project plan.

////
Backlog and Board Views
Planner provides you two views to track your work items:
The backlog or list view: This lists your work items in a flat or tree (hierarchical) structure. The tree structure enables you to see a work item, its parent and child work items. This helps you to order and prioritize your work.

The board view: This displays your work items in a kanban based board view. The work items are categorized on the basis of their completion status enabling easy tracking of your work items.
////
