[id="about_work_items"]
= About work items

Work items are measurable units of work within a link:user-guide.html#about_spaces[space] that can be tracked. They are captured representations of work, assigned to a team member. Work items track data such as user stories, scenarios, tasks, and bugs.

The {osio} planner is a task or work item tracker to plan and execute your project work. It includes a set of predefined planning templates based on common development methodologies such as _Agile_ and _Scenario Driven Development_. These templates determine the structure and features of the work item types and states available for a space.

Work items can be grouped and categorized into various work item types depending on the template you select for a space. These work items can then be scheduled to be completed within respective link:user-guide.html#about_iterations[Iterations] to track their progress.

Thus you can plan, execute, and track your development work based on the project management methodology you adopt.

////
Backlog and Board Views
Planner provides you two views to track your work items:
The backlog or list view: This lists your work items in a flat or tree (hierarchical) structure. The tree structure enables you to see a work item, its parent and child work items. This helps you to order and prioritize your work.

The board view: This displays your work items in a kanban based board view. The work items are categorized on the basis of their completion status enabling easy tracking of your work items.
////
