[id="about_pipelines_stage_run"]
= About pipelines and the stage and run environments

When you create a codebase, a pipeline build is initiated. Pipelines are automated, continuous integration and deployment processes, powered by Jenkins, which define how your application is deployed.

The free OpenShift Online Starter subscription, included with your {osio} subscription, provides two environments named _Stage_ and _Run_ to deploy your applications.

Initially, the build pipeline deploys the application to _Stage_, which is accessible to stakeholders for review through a public URL provided by OpenShift Online. If approved and promoted, the pipeline deploys it to the _Run_ environment. This simulates the workflow of pushing an application to a staging environment and reviewing it, before promoting it to production.

The _Run_ environment is similar to a production environment but is another staging area. The reason _Run_ is not named _Production_ is that the OpenShift Online Starter subscription does not support running production applications.
//See link:https://www.openshift.com/pricing/index.html[purchasing an OpenShift Online Pro subscription] for information about support for running production applications.
