[id="about_stage_run"]
= About the stage and run environments

Next, you will learn about pipelines and staging environments in {osio}. After you create or add an application to your space, a pipeline is created to publish your application.

When you get an {osio} subscription, you also get an OpenShift Online Starter subscription, which includes two environments named *Stage* and *Run* to deploy your applications. Initially, applications deploy to *Stage*, which is accessible to stakeholders for review using a public URL. If approved and promoted, the application deploys to *Run*, which is similar to a production environment but is another staging area.

The reason *Run* is not named *Production* is that the OpenShift Online Starter subscription does not support running production applications. See link:https://www.openshift.com/pricing/index.html[purchasing an OpenShift Online Pro subscription] for information about support for running production applications.

{osio} includes a *Stage* and *Run* environment to allow developers to experience the modern workflow of pushing an application to a staging environment before production. As a result, *Run* is a pseudo-production environment for educational purposes.
