[id="adding_description_to_a_work_item"]
= Adding description to a work item

You can describe the details for your work item as follows:

. In the *Description* field, click in the text box to add description for the work item.
. Click *Preview* to see the rendered markdown for your description, if you are satisfied, click *✓* to save the description.

NOTE: Click the pencil icon to edit a saved description.

////
This feature was taken off as per the latest PR, it may resurface, in what way, not clear as yet. Hence adding here, instead of creating another module for the same.
== Create links with other work items

You can see existing links or create links to other work items establishing relations between them as follows:

. Expand the *Links* option to see the work items linked to this work item.
. To create new links to work items click *Create Link*.
. Use the *Select Link Type* drop-down list to select the appropriate relationship between the two work items. You have the following options: *blocks*, *relates to*, *parent of*, *blocked by*, *is related to*, *child of*.
. In the *Search for work items* field, type the title or the ID of the required work item and select one of the listed suggestions.
. Click *Link* to save the relationship.

The linked work item is now listed under *Links*.
////
