[id="changing_your_password"]
= Changing your password

In the {osio} dashboard view, use the following steps to change your password:

. Navigate to your *Profile* view:

.. Click your name on the upper-right corner of the screen.

.. Click *Profile* from the displayed options.
. In the *Profile* screen, click btn:[Edit Profile] to edit your profile.
. In the edit profile screen, click btn:[Change password]. You are redirected to the Red Hat Developer *Log In* page.
//Raised a bug for the following round about way to reach the 'Reset your password' screen
. Click the btn:[Forgot your password] button. The *Reset Your Password* page is displayed.
. Enter your username or email address to receive instructions on changing your password in a mail.
. In the mail you receive, click the link to reset your credentials.
. Fill in the required details and add your new password to the appropriate field and click btn:[SUBMIT] to save the changes.

You have now successfully changed your {osio} password.
