[#configuring_pipelines]
= Configuring Pipelines

Advanced users can change the settings for their project's pipeline builds in OpenShift Online. For most users, we do not recommend changing the default values {osio} sets up.

.Prerequisites

. Ensure that you have created a build pipeline for your project. See <<creating_a_new_pipeline>> for instructions.

.Procedure

. Navigate to your Space's dashboard.
. Click btn:[Create].
. Click btn:[Pipelines]. The `Pipelines` page lists all the pipeline builds for your project.
. Click btn:[Edit Pipeline] for the target pipeline build.
. Enter your OpenShift Online credentials when prompted. When successful, you are redirected to your OpenShift Online account's Console.
+
WARNING: {osio} sets up the required default options for your pipeline build. We do not recommended changing these default settings.
+
. In this page, you can edit the following attributes for your build pipelines:
.. Use the `Source Configuration` section to edit your project's Git Repository URL.
.. Use the `Jenkinsfile Type` option to select the source of your Jenkinsfile for the build.
.. Use the `Jenkinsfile Source Path` option to provide a relative path to your Jenkinsfile.
. When ready, click btn:[Save] to save your changes.
