[id="creating_a_new_work_item"]
= Creating a new Work Item

The space template you select determines the structure of the guided work item type hierarchy, the work item types available for a space, and their features.

The fastest way to create work items in the planner is to use the quick-add option.

.Prerequisites

* <<creating_a_new_space,Create a new space>> or select an existing space with the required template.

.Procedure

. Select the *Plan* tab at the top of the page to view the planner. The default *Backlog* view displays the top level work item type group for your space.
. In the *Add Work Item* pane, select the required work item type from the work item type drop-down list. The space template determines the available work item types.
. Specify an appropriate title for the work item in the *Work Item Title* field.
. Click btn:[Add] or press kbd:[Enter] to create the work item. Alternatively, to add further details to the work item, click btn:[Add and open] to create the work item and see the detailed view for the work item.
//See Viewing and modifying work item for further details.


include::using_guided_hierarchy_to_create_work_item.adoc[leveloffset=+1]
