[glossary]
[id="glossary"]
= Glossary

This glossary provides concise definitions of terms and explanations of concepts used in Red Hat OpenShift.io and in related documentation.

////

Rules for this file:

This file is consumed for the automatic generation of infotips used by OSIO web components. Certain rules need to be observed.

* Only use the AsciiDoc syntax for a definition list to define terms.
* Don't capitalize terms arbitrarily.
* Use singulars for term names.
* Each term needs to be bracketed in the following:

  // term: $uuid, en
  // endterm

* When adding a new term, either use the `uuidgen` command on the CLI or use  https://www.uuidgenerator.net/ to generate a new UUID.
* Never change existing UUIDs; even when correcting the name of the term.
* Never remove terms, unless first agreed on with the respective OSIO team that uses its definition.
* Alphabetize the terms for easy orientation.
* Use $ ./scripts/export_infotips.sh to update json file.
* Use $ cat json/infotips.json | jq to verify the updated json and then add, commit and push both glossary.adoc ans the json file.

////

// term: 6cff4ab8-c380-4aa9-9980-17b6f223d181, en
alternate dependency:: Dependencies recommended by OpenShift.io to replace restrictive licenses or usage outliers.
// endterm

// term: a99bf72a-baf4-436e-8095-3955e39d5af0, en
area:: Use areas to organize work items to distinguish between different types or functionalities that are being worked on within a space.
// endterm

// term: d6c3bc51-f623-4aa4-bea4-4e1d68a27661, en
backlog:: A backlog is a list of work items that have not been triaged and assigned to a specific iteration.
// endterm

////
// term: ad7b1eb4-b385-4eb8-b1ea-9c447aa5bf0b, en
backlog items:: Work item type group that focuses on the execution oriented work item types such as product backlog item, task, and bug.
// endterm
////

// term: 26787039-b68f-4e28-8814-c2f93be1ef4e, en
bug:: A defect that causes unexpected behavior in the software and that needs to be fixed.
// endterm

////
// term: 90e961d1-0de8-49f4-b197-ba13418c20a8, en
(scrum) bug:: A defect that causes unexpected behavior in the software and that needs to be fixed.
// endterm
////

// term: 1694e637-2f9b-40ec-8fa8-a22472850ff9, en
companion dependency:: Based on the analysis of your stack, {osio} suggests additional dependencies that can add value to your stack.
// endterm

// term: f450d7d0-3d38-4887-83ca-38d27c109b59, en
epic:: A big chunk of work with a common objective that may take many iterations to deliver. It is split into multiple features and backlog items that try to satisfy the different aspects of the epic.
// endterm

////
// term: d0d33acf-7629-4653-9551-97ed9156f127, en
(wig) epic:: A big chunk of work with a common objective that may take many iterations to deliver. It is split into multiple features and backlog items that try to satisfy the different aspects of the epic.
// endterm
////

// term: b9a71831-c803-4f66-8774-4193fffd1311, en
experience:: An experience is a way to address a scenario, fundamental, or a set of papercuts, each of which often have multiple realizing experiences. Often written as a demonstration script, it describes the ideal end-user work flow for realizing one or more of the associated value propositions.
// endterm

////
// term: 6d254168-6937-447f-a093-0c38404bd072, en
experiences:: Work item type group that focuses on the experience and value proposition work item types that address the scenarios.
// endterm
////

// term: 0a24d3c2-e0a6-4686-8051-ec0ea1915a28, en
feature:: Features, often expressed as user stories, are required to actualize parent experiences or epics. They are scoped so that they are generally achievable within a sprint.
// endterm

////
// term: 83852318-a69a-4092-a412-bb67527c4ba6, en
(scrum) feature:: Features, often expressed as user stories, are required to actualize parent experiences or epics. They are scoped so that they are generally achievable within a sprint.
// endterm
////

////
// term: 9e41be6f-9e16-4e39-bb46-bd130855f2e5, en
(wig) feature:: Features, often expressed as user stories, are required to actualize parent experiences or epics. They are scoped so that they are generally achievable within a sprint.
// endterm
////

// term: ee7ca005-f81d-4eea-9b9b-1965df0988d0, en
fundamental:: A fundamental describes the basic essentials of a software product, such as quality and performance standards. It is a non-negotiable aspect of a product and its absence reduces the value provided to the user.
// endterm

////
// term: fca1397f-cd58-4f12-ad22-0cce8451a764, en
impediment:: An impediment is anything that affects team performance or progress. It may include high probability risks that are likely to occur fairly soon.
// endterm
////

////
// term: d5bd6f64-cee4-46d7-9b12-b3cb5e70145e, en
issue:: An issue is an unmet user expectation, an observation that something doesn't work as one expects it to. It could represent bugs, feature requests, or enhancements and are linked to an appropriate work item in the backlog as part of the triage process. // endterm
////

// term:  5c3ee317-3cdd-4ee6-a27f-85965f777ee3, en
iteration:: A development cycle used to organize, plan, and execute work items in a certain order. It comprises a logical mix of work items slated to be executed within the time frame of the iteration.
// endterm

////
// term: 4d187330-0efb-4077-8745-8a61384a6540, en
(scrum) iteration:: A development cycle used to organize, plan, and execute work items in a certain order. It comprises a logical mix of work items slated to be executed within the time frame of the iteration.
// endterm
////

// term: f05a151a-61fa-45b1-8d8b-b3fd7bc63ea9, en
license conflict:: Licenses that conflict at the stack or dependency level.
// endterm

// term: 6d603ab4-7c5e-4c5f-bba8-a3ba9d370985, en
papercut:: A papercut is a minor issue, often too small to be individually prioritized to be addressed; collectively, papercuts degrade the perception of the product. Grouped together, they receive higher priority and can be tackled together within a development cycle.
// endterm

// term: 5bd840a6-2f62-4bea-bb04-63252f6ce381, en
pipeline:: Pipelines are a continuous delivery system that, at each step, tests and deploys the code to provide feedback to the user. Examples of such steps are unit testing, performance, integration, and deployment. Each step of the pipeline implements different levels of testing and deployment tasks, provides results, and then passes the code on to the next step.
// endterm

// term: 23b1dfd5-f497-4843-97c3-e3eefdc9930e, en
product backlog item:: A small unit of work that can be completed by a team within an iteration and that can be broken down into tasks. It is commonly described in the format of a user story, with clearly specified requirements, an owner, an estimated size, and ordered based on the order of execution.
// endterm

// term: 3a953b07-0cc3-4b45-b891-bf490216eae3, en
restrictive license:: Licenses that are not commonly used in similar stacks or that do not work well with the stack’s representative license.
// endterm

// term: 44795662-db7a-44f7-a4e7-c6d41d3eff27, en
requirement:: Work item type group that focuses on execution oriented work item types such as feature, task, and bug.
// endterm

// term: 71171e90-6d35-498f-a6a7-2083b5267c18, en
scenario:: A scenario identifies a real-world user problem to resolve. Addressing the scenario provides tangible user value. Prioritize scenarios that deliver maximum user value by evaluating their associated value propositions.
// endterm

////
// term: 679a563c-ac9b-4478-9f3e-4187f708dd30, en
scenarios:: Work item type group that focuses on the planning oriented work item types such as scenario, fundamental and papercuts.
// endterm
////

// term: eb05f2b6-8a3c-4054-b28c-3eb1a47c125f, en
scenario driven development:: An agile development methodology focused on real-world problems, or scenarios, described in the language and from the viewpoint of the user. Scenarios deliver particular value propositions and are realized through experiences.
// endterm

// term: d6cb8344-ce3b-4aed-b517-78303d253bcf, en
scrum:: An iterative and incremental agile software development framework for managing product development.
// endterm

// term: a5fad1f2-7d5c-4d62-b269-d3637495422a, en
security issue:: OpenShift.io analyzes the CVEs of all your dependencies and flags the ones with security vulnerabilities.
// endterm

// term: 5c543e22-8ae9-4b66-9112-1513d47ab1b4, en
space:: A space is the equivalent of a project. Each iteration and work item must be attached to a space, and a team of people can be attached to a space in various roles. By default, a space contains at least one area and one iteration.
// endterm

// term: bbf35418-04b6-426c-a60b-7f80beb0b624, en
task:: Work assigned to various team members to implement a feature. They are generally measured in units of 0.5 days, for example, four hours, eight hours, sixteen hours.
// endterm

////
// term: db906e00-a5fa-4a86-8ef7-772c89f703ac, en
(scrum) task:: Work assigned to various team members to implement a feature. They are generally measured in units of 0.5 days, for example, four hours, eight hours, sixteen hours.
// endterm
////

// term: 0b52988d-9cea-47a6-9769-d677bff95ed3, en
unknown license:: Licenses unknown to OpenShift.io.
// endterm

// term: 203160dd-cb50-4383-a2d6-84efcd472c98, en
usage outlier:: Dependencies in your stack that are not commonly used in similar open source stacks or that rarely work well together.
// endterm

// term: 3194ab60-855b-4155-9005-9dce4a05f1eb, en
value proposition:: A statement of the value provided to the user by addressing a scenario, fundamental, or papercut. Each of which can have multiple value propositions.
// endterm

// term: 83e7953e-9335-428c-b1af-7aa4b00cd662, en
work item:: Work items describe and keep track of work that needs to be completed. They can be assigned to collaborators within a space. Each work item must be attached to a space and an area (assigned by default). This can be used to model bugs, tasks, features, ideas, and more.
// endterm

// term: e4c8beb4-1ed1-4275-af20-9ee3cb6dafd1, en
workspace:: Workspaces are fully configured web-based development environments suitable for your code and runtime needs. They are runtime environments where you can modify, test, debug, or run your code.
// endterm
