[glossary]
[id="glossary"]
= Glossary

This glossary provides concise definitions of terms and explanations of concepts used in Red Hat OpenShift.io and in related documentation.

////

Rules for this file:

This file is consumed for the automatic generation of infotips used by OSIO web components. Certain rules need to be observed.

* Only use the AsciiDoc syntax for a definition list to define terms.
* Don't capitalize terms arbitrarily.
* Use singulars for term names.
* Each term needs to be bracketed in the following:

  // term: $uuid, en_EN
  // endterm

* When adding a new term, either use the `uuidgen` command on the CLI or use  https://www.uuidgenerator.net/ to generate a new UUID.
* Never change existing UUIDs; even when correcting the name of the term.
* Never remove terms, unless first agreed on with the respective OSIO team that uses its definition.
* Alphabetize the terms for easy orientation.

////

// term: 6cff4ab8-c380-4aa9-9980-17b6f223d181, en_EN
alternate dependency:: Dependencies recommended by OpenShift.io to replace restrictive licenses or usage outliers.
// endterm

// term: a99bf72a-baf4-436e-8095-3955e39d5af0, en_EN
area:: Use areas to organize work items to distinguish between different types or functionalities that are being worked on within a space.
// endterm

// term: d6c3bc51-f623-4aa4-bea4-4e1d68a27661, en_EN
backlog:: A backlog is a list of work items that have not been triaged and assigned to a specific iteration.
// endterm

// term: e8d54bf3-f89e-46e5-86f7-4af6475863b0, en_EN
bug:: Defect that causes unexpected behavior in the software.
// endterm

// term: 1694e637-2f9b-40ec-8fa8-a22472850ff9, en_EN
companinon dependency:: Based on the analysis of your stack, {osio} suggests additional dependencies that can add value to your stack.
// endterm

// term: 23c322f1-53b1-4286-b524-37ab58124823, en_EN
experience:: Experience describes the envisioned user experience in the product to actualize a parent work item. Each parent work item can have multiple experiences.
// endterm

// term: dbfc82e1-5a40-44bd-af70-f2dc1a1927a4, en_EN
feature:: A feature is a detailed user-story that helps actualize parent experiences. It can support multiple experiences and is generally achievable within a sprint.
// endterm

// term: e8d54bf3-f89e-46e5-86f7-4af6475863b0, en_EN
bug:: Defect that causes unexpected behavior in the software.
// endterm

// term: 4d85adba-817d-41ca-b85f-1e4a938d1282, en_EN
fundamental:: Work item type that focuses on getting the basic foundations of a product right to make it more efficient.
// endterm
////

// term: 5c1b8158-a351-4092-8780-3ad22e1eb173, en_EN
iteration:: An iteration is used to organize, plan, and execute work items in a certain order. It comprises a logical mix of work items slated to be executed within the time frame of the iteration.
// endterm

// term: f05a151a-61fa-45b1-8d8b-b3fd7bc63ea9, en_EN
license conflict:: Licenses that conflict at the stack or dependency level.
// endterm

//// term: 83b7cf12-558e-41bd-bcd7-822ca6307db1, en_EN
papercuts:: Papercuts are logical aggregations of minor issues that collectively have a negative impact on the user. This aggregation receives higher priority and enables efficient handling of such issues.
// endterm
////

// term: 5bd840a6-2f62-4bea-bb04-63252f6ce381, en_EN
pipeline:: Pipelines are a continuous delivery system that, at each step, tests and deploys the code to provide feedback to the user. Examples of such steps are unit testing, performance, integration, and deployment. Each step of the pipeline implements different levels of testing and deployment tasks, provides results, and then passes the code on to the next step.
// endterm

// term: 3a953b07-0cc3-4b45-b891-bf490216eae3, en_EN
restrictive license:: Licenses that are not commonly used in similar stacks or that do not work well with the stack’s representative license.
// endterm

// term: 01e76137-ab89-4a3c-8765-48f54078154a, en_EN
scenario:: Work item type that identifies and tries to resolve real world problems faced by users, mostly defined in a broad sense.
// endterm
////

// term: eb05f2b6-8a3c-4054-b28c-3eb1a47c125f, en_EN
scenario-driven planning:: A software development methodology focused on real-world problems, or scenarios, described in the language and from the viewpoint of the user. Scenarios deliver particular value propositions and are realized through experiences.
// endterm

// term: a5fad1f2-7d5c-4d62-b269-d3637495422a, en_EN
security issue:: OpenShift.io analyzes the CVEs of all your dependencies and flags the ones with security vulnerabilities.
// endterm

// term: 5c543e22-8ae9-4b66-9112-1513d47ab1b4, en_EN
space:: A space is the equivalent of a project. Each iteration and work item must be attached to a space, and a team of people can be attached to a space in various roles. By default, a space contains at least one area and one iteration.
// endterm

// term: cc2d6cb4-7690-4c02-989c-7d75e3419b7d, en_EN
task:: Work assigned to various team members to implement a feature. They are generally measured in units of 0.5 days, for example, four hours, eight hours, sixteen hours.
// endterm

// term: 0b52988d-9cea-47a6-9769-d677bff95ed3, en_EN
unknown license:: Licenses unknown to OpenShift.io.
// endterm

// term: 203160dd-cb50-4383-a2d6-84efcd472c98, en_EN
usage outlier:: Dependencies in your stack that are not commonly used in similar open source stacks or that rarely work well together.
// endterm

// term: 83e52577-cdc4-4687-97d1-86151db74bdc, en_EN
value proposition:: Work item type that states the value provided to the user by addressing a parent work item. Each parent work item can have multiple value propositions.
// endterm

// term: 83e7953e-9335-428c-b1af-7aa4b00cd662, en_EN
work item:: Work items describe and keep track of work that needs to be completed. They can be assigned to collaborators within a space. Each work item must be attached to a space and an area (assigned by default). This can be used to model bugs, tasks, features, ideas, and more.
// endterm

// term: e4c8beb4-1ed1-4275-af20-9ee3cb6dafd1, en_EN
workspace:: Workspaces are fully configured web-based development environments suitable for your code and runtime needs. They are runtime environments where you can modify, test, debug, or run your code.
// endterm
