[#importing_a_codebase]
= Importing a Codebase

Use the `Import Codebase` option to manually add the details for your existing codebase into {osio}.

. Click btn:[Import Codebase].
. In the *Space Path* field, If required, change the path to your Collaboration Space.
. In the *GitHub Repository* field, add the GitHub repository path
. Click *Sync* to retrieve details for the repository. If the sync is successful, metadata for the added repository appears below the btn:[Sync] button.
. Click btn:[Associate Repository to Space] to add the new repository to your Collaboration Space. The *Create* tab now displays your new repository with information about when it was created and the last commit date.
. Click btn:[Create a Workspace] for the target repository from the displayed list. A success message appears when the Workspace is successfully created.
+
[NOTE]
====
Ensure that your browser allows pop-ups from this page. The Eclipse Che context requires a new tab to start.
====
+
. In the drop-down menu, select the new Workspace for your repository, then click *Open*. A new browser tab loads and displays the Eclipse Che context with your repository codebase.
