[id="importing_your_codebase-{context}{secondary}"]
= Importing your codebase

After creating a space, use the *Create an Application* wizard to import an existing codebase to create a new application. If you closed the wizard earlier, click btn:[Add to space] in the upper-right corner of your space dashboard.

. In the *Name your application* field, type a unique name for your new application.
. Select the *Import an existing codebase* radio button and then click btn:[Continue] to import an existing project codebase into {ct}.
//. The *Import an existing codebase* radio button is auto-selected since you clicked btn:[Import Existing Codebase] when you first created the space. Click btn:[Continue] to import an existing project codebase into {ct}.
. In the *Authorize Git Provider* step:

.. Click the *Location* drop-down to select the location of your codebase. The default option is your personal GitHub account name.
.. In the *Repository* field, click *Select Repository* to select the repository from which you want to import the codebase.
.. Click the blue arrow at the bottom of the screen to continue.
. In the *Select pipeline* step, select an option for your pipeline build, then click the blue arrow to continue to the next step. We recommend using the first option for most use cases because it provides an end to end pipeline that is suitable for most projects.

. The *Confirm Application Summary & Import* step displays a summary for your imported code. Review the information and click btn:[Import Application] to confirm. The progress screen displays when the code is successfully imported.
. Click btn:[View New Application] to continue when all the steps have a green check mark next to them.

You have now imported the code from your existing repository to {ct}.
