[id="introduction"]
= Introduction

Thank you for your interest in {osio}! The purpose of this document is to guide you through your first experiences with {osio}. Following the instructions in this document, you can set up an application running in the cloud within minutes. Shortly thereafter you will have customized and then deployed a new version of that application.

//{osio} is constantly being updated and therefore improving as you use it, and we would love to hear from users to make it a better experience for you. Updates and changes to the system are delivered continuously, often dozens of times each day. As a result, features and elements of the user interface change often and, yes, sometimes bugs are a part of that delivery -- bugs which can, at times, be severe and take the entire system offline. However, as part of our continuous delivery model, everyone who pushes a change out to the live system assumes responsibility for the impact of that change, so even the severe bugs are addressed quickly. A more important aspect of the Early Access Program is to get your feedback. Tell us what you like, what you hate, what you wish you could do, what you wish the service would stop doing, etc. Everything is fair game. See the <<providing-product-feedback>> section for information on how to contact us.
//update this text

If your {osio} environment gets into a state where you are finding it difficult or impossible to move forward, refer to the <<cleaning_oso_account>> section of this document for information on how to factory reset your {osio} (and OpenShift Online) environment. Welcome to the world of {osio}! We hope you enjoy your experience and look forward to hearing your feedback!

[id="about-this-document"]
== About this document

The purpose of this getting started guide is to walk you through your initial set up of {osio} and quickly expose you to some key functionality in {osio}. If this document is successful, the majority of first time {osio} users will have a custom, albeit simple, application running on the internet in under one hour.
