[id="next_steps"]
= Next steps

If you followed the instructions in this document, you have now learned about {ct} and its features. You are now able to:

* Create spaces for your projects. See <<creating_new_space-hello-world>>.
* Add code from an existing project to your space. See <<importing-existing-project>>.
* Create new projects using the quickstart wizards and test them. See <<hello_world_developers>> for a Vert.X project.
//and <<spring_boot_quickstart_tutorial>> for a Spring Boot project.
* Plan your work by creating work items and execute them using iterative development cycles. See <<planning_development_work>>.
* Use the build pipelines to stage reviews in the *Stage* and *Run* environments. See <<reviewing_your_staged_application>> and <<approving_your_application>>.
* Create Che workspaces to edit your project code and commit the changes to GitHub. See <<creating_che_workspace-hello-world>> and <<committing_pushing_changes_git-hello-world>>.
* Optimize the memory usage for your projects to use your OpenShift Online resources more efficiently. See <<optimizing_memory_usage>>.
// and <<reducing_project_memory_usage-spring-boot>>.
* Use stack reports to make improvements to your code. See <<using_stack_reports_to_analyze_your_application>>.
* Debug your code using the Che workspace. See <<debugging_using_che_workspace>>.
* Clean up your {ct} account so you can start afresh. See <<resetting_your_ct_account>>.

You can now try using what you have learned about {ct} with your own projects. See the link:user-guide.html[{ct} User Guide] for comprehensive information about {ct} and its features. If you have any questions or suggestions for improvement with {ct} or this document, let us know using one of the methods listed in <<getting_help_and_giving_feedback>>.
