[id="red_hat_openshift_io_overview"]
= {rhosio} overview

{rhosio} is a highly collaborative open-source, web-based _application life cycle management_ (ALM) solution. It is a next-generation product for developers to manage the development life cycle with one efficient tool. It enables you to plan, create, and deploy hybrid cloud services. It utilizes many open source projects like fabric8, Eclipse Che, and OpenShift Online.

== Features

{osio} offers features to seamlessly manage end-to-end application development. It provides an integrated approach to DevOps with all the tools necessary to analyze, plan, create, and deploy services. Members of distributed teams can use it to perform the following tasks without leaving the browser window:

*Project management:*

* Plan your projects and track issues using your choice of Agile methodology.
//* Automating project releases.<Check with devs if this can be done>
* Minimize effort on building and maintaining a development tool chain.

*Project development:*

* Create containerized development, testing, and staging environments hosted on OpenShift Online.
* Code, edit, and debug using an integrated development environment based on Eclipse Che, which provides a workspace for developing and managing your application. This context-aware environment provides the appropriate context, such as the referenced branch, repository, language, and files, for the developer and the project.
* Interact with integrated GitHub repositories.
* Compile and review code in Pull Requests as required.
* Use the quick start wizards to create basic applications with repositories on GitHub, integrated Jenkins pipelines plugins, and a related new OpenShift project.
* Use the importing codebase wizard to migrate legacy J2EE applications to the cloud.

*Deployment and testing:*

* Build, test, deploy, and monitor codebases using continuous integration pipelines that can be tailored to the requirements of a team - you can have simple automated build pipelines or add manual promotions.
* Deploy applications packaged as a set of containers to OpenShift, which powers the underlying services such as the Eclipse Che workspaces and pipelines.
* Use integrated but customizable Jenkins build pipelines to facilitate rapid testing and environment promotion, reducing your build and maintenance efforts.

*Analysis and recommendations:*

* Use the full-stack analysis feature on the software components in your application to identify potential security issues in your source code and get suggestions on safer alternative components to use instead.
* Use the self-learning analytics engine to improve the code quality and make data-based choices. The engine scans community libraries, security vulnerabilities, and other GitHub metrics to provide useful real-time assistance for developers that learns and improves over time.

//== Support
//Update after checking with Brad/Gorkhem
//Red Hat currently does not offer a support subscription for {osio}. The service is available as a free _Developer Preview_ for open-source projects and developers.
