[id="resetting_your_ct_account"]
= Resetting your {ct} account

{ct} generates artifacts in five OpenShift Online projects (Kubernetes namespaces). See link:getting-started-guide.html#viewing_projects_oso[Viewing projects in OpenShift Online] for details.

Resetting your {ct} account frees up all your OpenShift Online resources. This option is used in the following situations:

* If you have followed the instructions in this document, you have created two quickstart projects in {ct}. Your OpenShift Online Free Tier account resources are limited and therefore you must reset your account to create a new project.

* If your {ct} environment is in a state where it is difficult or impossible for you to move forward, resetting your environment lets you remove everything and start again.

Reset your {ct} account as follows:

. On your {ct} home page, click your name in the top right corner of the screen.

. In the drop-down options, click *Profile*.

. On the profile page, click btn:[Edit Profile].

. In the edit profile page, click btn:[Reset Environment]. A warning page appears with a summary of your {ct} account.

. Click btn:[Erase my {ct} Environment].

. In the dialog box, add your {ct} user name and click btn:[I understand my actions - erase my environment]. After the environment is reset, the success page displays.

. Click btn:[Take me to my Dashboard] to return to your {ct} dashboard.

After completing these steps, your {ct} and OpenShift Online account resources are reset and ready for use with a new project.
