[id="signing_up_for_the_red_hat_developers_program"]
= Signing up for the Red Hat Developers Program

To start using {rhosio}, create a new Red Hat Developers (RHD) account or use an existing RHD or social media account.

. Navigate to link:{osio-url}[{rhosio}].

. Click btn:[Sign Up]. You can register using an existing social or Red Hat account.

  * To register a new Red Hat account:
    ... At the {rhosio} Developer page, click btn:[Register].
    ... Enter your name, email address, company, and password in the appropriate fields.
    ... Select the terms and conditions check boxes.
    ... Click btn:[Create my account].
    ... Verify your email address to complete registration.

  * To register using your existing Red Hat account or a social account from services such as JBoss Developer, GitHub, Stack Overflow, LinkedIn, Twitter, Facebook, Google, or Microsoft:
    ... Click the appropriate social account button.
    ... Add your login credentials for the selected service and authorize the creation of the account.

== Related information

The following links provide additional resources about accessing Red Hat's offering for developers:

* link:https://developers.redhat.com/articles/red-hat-developer-program-benefits/[Red Hat Developer Program Benefits]
* link:https://www.redhat.com/en/store/red-hat-enterprise-linux-developer-suite[Red Hat Enterprise Linux Developer Suite]
* link:https://www.redhat.com/en/store/red-hat-enterprise-linux-developer-workstation[Red Hat Enterprise Linux Developer Workstation]
* link:https://www.redhat.com/en/store/red-hat-enterprise-linux-developer-support[Red Hat Enterprise Linux Developer Support]
