[id="using_detailed_method_to_create_work_items"]
= Using the detailed method to create work items

The detailed method requires adding more details for the work item compared to the quick-add method, which only requires basic information to create the work item.

. Click btn:[Analyze] to view the space dashboard.

. In the *My Work Items* panel, click btn:[+].

. Click the desired work item type.

. In the new work item form:

.. Add a title for the work item and click &#10003; or press *Enter* to save the new work item. This creates a new work item. You must save each of the subsequent changes to fields individually.

.. Assign the work item to a collaborator in the *Assignees* field. The assignee field for a new work item is empty as a default.

.. Assign an <<about_areas,area>> to the work item from the *Area* field drop-down list and click &#10003; to save the change. By default, the name of your workspace is set as the _Root Area_ and is displayed as one of the options in the drop-down list.

.. Assign a relevant <<about_iterations,iteration>> to the work item from the *Iteration* drop-down list and click &#10003; to save. By default, the name of your workspace is set as the _Root Iteration_ and is displayed as one of the options in the drop-down list.

.. Click btn:[Add label] to add existing or new labels to your work item.

.. Add a description for the work item in the *Edit Text* field and click &#10003; to save.

.. Optionally, expand the *Total links* option to link to other related work items as follows:

... Click the btn:[Create Link] button.

... Use the btn:[Select Link Type] drop-down menu to select the appropriate relationship between the current and new work item.

... Start typing the title or ID of a work item in the *Search for work items* field. Select one of the listed suggestions.

... Click btn:[Link] to save the relationship.

.. Optionally, expand the *Comments* option to add or see comments for your work item. Users can edit or delete their own comments.

. To close the new work item panel:

.. Ensure that all your changes are individually saved.

.. Click btn:[x] at the top of the panel.

