[id="viewing_the_pipeline_projects_in_oso"]
= Viewing the Pipeline Projects in OpenShift Online

To view the OpenShift Online projects that support your project pipeline, navigate to link:https://console.starter-us-east-2.openshift.com/[console.starter-us-east-2.openshift.com]. This page displays the following projects (or namespaces) that are created in OpenShift Online:

* The _username_ project is where your pipelines run. This project name is your OpenShift Online user name.
* The _username-che_ project is for your Che Host and workspaces.
* The _username-jenkins_ project runs your Jenkins Master or your Jenkins Slaves. Click btn:[Monitoring] after clicking this project to access your Jenkins console.
* The _username-stage_ project is for your personal use. In this project, pods display as running or previously run pipelines. For maintenance, click this project and power down individual pods as required.
* The _username-run_ project is identical to the _username-stage_ project and is an environment for experimenting with your OpenShift pods.
