[#working_with_an_existing_work_item]
= Working with an Existing Work Item
//redo this, stopped here
Use the Planner in the *Plan* tab to track your Work Items and Iterations using either the list view or the board view. The *Plan* tab is split into two panes:

* The left pane displays the *Backlog* and *Board* views of Iterations and Work Items. For more information see <<about_iterations,About Iterations>>.
* The right pane displays the Work Items within the selected Iteration or the backlog.

You can plan and track your Work Items in the right pane using either the hierarchical or flat list view of Work Items on the menu:Plan[Backlog] subtab or the Kanban-based board view on the menu:Plan[Board] subtab.

The *Plan* tab enables you to modify the attributes of a Work Item, associate them with Iterations, order and monitor their progress and filter them as per your requirements.


[#modifying_an_existing_work_item]
== Modifying an Existing Work Item

You can modify an existing Work Item after it has been created by clicking on an existing Work Item in the list or board view.

Alternatively, click the menu adjoining the Work Item and select *Open* from the displayed options. The detailed Work Item panel is displayed.

The following attributes of a Work Item can be modified:

* Status
* Owner
* Area
* Iteration
* Description
* Relations with other Work Items
* Comments

+
See <<using_the_detailed_method>> for more information on modifying the above attributes.


[#associating_work_items_with_an_iteration]
== Associating Work Items with an Iteration

To associate a Work Item with an Iteration:

. Click the menu adjoining the Work Item and select *Associate with Iteration* from the displayed options. The *Associate with Iteration* dialog box is displayed.

. From the *Select iteration* drop-down list, select the Iteration you want to associate your Work Item with and click the btn:[Reassociate] button.

Selecting a particular Iteration on the left pane will display Work Items associated with that Iteration.

To move Work Items to the *Backlog*, click the menu adjoining the Work Item and select *Move to Backlog* from the displayed options. You can select *Backlog* to display all the Work Items within a Space.


[#ordering_and_monitoring_work_items]
== Ordering and Monitoring Work Items

The *Backlog* subtab provides a list view enabling you to plan your work by ordering the Work Items based on their priority, status, and other such parameters.

The *Backlog* subtab can display the list of Work Items as:

* A *Hierarchy*, or in a tree-view format where child Work Items are displayed only when you expand the parent Work Item or

* A *Flat* list, where all the Work Items are displayed in a single file.

You can order the Work Items in the list based on your requirement as follows:

* In the menu:Plan[Backlog] subtab, select and drag & drop a Work Item based on the required order. Alternatively, select *Move to Top* or *Move to Bottom* from the Work Item menu.

The *Board* subtab provides a visual representation of the progress status of your Work Items. Based on their status, the Work Items are sorted into swim-lanes  as *new*, *open*, *in progress*, *resolved*, and *closed*. This enables you to track the status of the Work Item from its start to its completion.

You can order the Work Items in the board based on the status of the Work Item as follows:

* In the menu:Plan[Board] subtab, select and drag & drop a Work Item to the relevant swim-lane based on the progress of the Work Item.


[#filtering_work_items]
== Filtering Work Items

In the *Backlog* subtab, you can filter Work Items on the basis of *Assignee*, *Area*, or *Work Item Type*.

* In the menu:Plan[Backlog] subtab, use the *Select* drop-down to filter and display relevant Work Items.
+

You can filter Work Items by:
+

** *Assignee*: Select an assignee from the *Filter by assignee* drop-down list to display Work Items assigned to a particular user.

** *Area*: Select an area from the *Filter by area* drop-down list to display Work Items belonging to a particular Area.

** *Workitem Type*: Select a Work Item Type from the *Filter by workitemtype* drop-down list to display Work Items belonging to a particular Work Item Type.

In the *Board* subtab you can filter Work Items similarly on the basis of *Assignee* or *Area* by using the *Select* drop-down list.

The *Board* view gives you the option to select a required Work Item Type in the *Currently showing* drop-down list to display Work Items relevant to that particular Work Item Type.
