---
apiVersion: v1
kind: Template
metadata:
  name: fabric8-online-docs
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 111c5596bec7c63f6881555eb400a9eb4557e134
      fabric8.io/git-branch: release-v1.0.7
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-apps/fabric8-online-docs-app.git
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-apps/fabric8-online-docs-app.git
      fabric8.io/scm-tag: fabric8-online-docs-app-1.0.0
      fabric8.io/scm-url: http://github.com/fabric8-apps/fabric8-online-docs-app
    labels:
      expose: "true"
      app: fabric8-online-docs-app
      provider: fabric8
      version: 1.0.7
      group: io.fabric8.apps
    name: fabric8-online-docs-app
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: fabric8-online-docs-app
      provider: fabric8
      group: io.fabric8.apps
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: fabric8-online-docs-app
      provider: fabric8
      version: 1.0.7
      group: io.fabric8.apps
    name: fabric8-online-docs-app
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 111c5596bec7c63f6881555eb400a9eb4557e134
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=fabric8-online-docs-app&var-version=1.0.7
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-apps/fabric8-online-docs-app.git
      fabric8.io/scm-url: http://github.com/fabric8-apps/fabric8-online-docs-app
      fabric8.io/git-branch: release-v1.0.7
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-apps/fabric8-online-docs-app.git
      fabric8.io/scm-tag: fabric8-online-docs-app-1.0.0
    labels:
      app: fabric8-online-docs-app
      provider: fabric8
      version: 1.0.7
      group: io.fabric8.apps
    name: fabric8-online-docs-app
  spec:
    replicas: 1
    selector:
      app: fabric8-online-docs-app
      provider: fabric8
      group: io.fabric8.apps
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 111c5596bec7c63f6881555eb400a9eb4557e134
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=fabric8-online-docs-app&var-version=1.0.7
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8-apps/fabric8-online-docs-app.git
          fabric8.io/scm-url: http://github.com/fabric8-apps/fabric8-online-docs-app
          fabric8.io/git-branch: release-v1.0.7
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8-apps/fabric8-online-docs-app.git
          fabric8.io/scm-tag: fabric8-online-docs-app-1.0.0
        labels:
          app: fabric8-online-docs-app
          provider: fabric8
          version: 1.0.7
          group: io.fabric8.apps
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 10
          name: nginx
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 1m
              memory: 20Mi
            limits:
              cpu: 400m
              memory: 1Gi
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: fabric8-online-docs-app
      provider: fabric8
      version: 1.0.7
      group: io.fabric8.apps
    name: fabric8-online-docs-app
  spec:
    to:
      kind: Service
      name: fabric8-online-docs-app
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-fabric8io-fabric8-online-docs
- name: IMAGE_TAG
  value: latest
